kind: project
spec:
  origin_url: git://github.com/HarshilShah1804/CS203_Assignment9.git#refs/heads/main
  functions:
  - url: ./load_data.py
    name: load-breast-cancer-data
    kind: job
    image: mlrun/mlrun
  - url: trainer.py
    name: trainer
    kind: job
    image: mlrun/mlrun
    handler: train
  - url: serving.py
    name: serving
    kind: serving
    image: mlrun/mlrun
  source: git://github.com/HarshilShah1804/CS203_Assignment9.git#refs/heads/main
  conda: ''
  desired_state: online
metadata:
  name: cs203-jovyan
